#!/bin/sh

# yodel v0.1.0
# a script for making formatted text output a bit more easy

case "$1" in
	--help)
		printf "yodel v0.1.0\n\n-b / --bold - prints \033[1mbold\033[m text\n-l / --light - prints \033[2mlight\033[m text\n-i / --italic - prints \033[3mitalic\033[m text\n-u / --underline - prints \033[4munderlined\033[m text\n-c / --color (red,green,yellow,blue,magenta,cyan) - print \033[31mcolored\033[m text\n-ci / --color-indexed [0-255] - print \033[38;5;123m255-color\033[m text\n-cr / --color-rgb [0-255] [0-255] [0-255] - prints full \033[38;2;255;0;0mR\033[38;2;0;255;0mG\033[38;2;0;0;255mB\033[m text\n-[x]n / -n[x] remove trailing newline\n"
	;;
	-b | --bold) # Bold
		printf "\033[1m%s\033[m\n" "$2"
	;;
	-l | --light) # Light
		printf "\033[2m%s\033[m\n" "$2"
	;;
	-i | --italic) # Italic
		printf "\033[3m%s\033[m\n" "$2"
	;;
	-u | --underline) # Underline
		printf "\033[4m%s\033[m\n" "$2"
	;;
	-c | --color) # A few predefined colors
		case "$2" in
			red)
				printf "\033[31m%s\033[m\n" "$3"
			;;
			green)
				printf "\033[32m%s\033[m\n" "$3"
			;;
			yellow)
				printf "\033[33m%s\033[m\n" "$3"
			;;
			blue)
				printf "\033[34m%s\033[m\n" "$3"
			;;
			magenta)
				printf "\033[35m%s\033[m\n" "$3"
			;;
			cyan)
				printf "\033[36m%s\033[m\n" "$3"
			;;
			*)
				printf "Unknown color\n"
			;;
		esac
	;;
	-cr | --color-rgb) # RGB
		printf "\033[38;2;$2;$3;$4m%s\033[m\n" "$5"
	;;
	-ci | --color-indexed) # Indexed colors i guess it wasn't hard to add
		printf "\033[38;5;$2m%s\033[m\n" "$3"
	;;
	-n) # printf with extra steps
		printf "%s" "$2"
	;;
	-nb | -bn) # Bold, no newline
		printf "\033[1m%s\033[m" "$2"
	;;
	-nl | -ln) # Light, no newline
		printf "\033[2m%s\033[m" "$2"
	;;
	-ni | -in) # Italic, no newline
		printf "\033[3m%s\033[m" "$2"
	;;
	-nu | -un) # Underline, no newline
		printf "\033[4m%s\033[m" "$2"
	;;
	-nc | -cn) # Colored, no newline
		case "$2" in
			red)
				printf "\033[31m%s\033[m" "$3"
			;;
			green)
				printf "\033[32m%s\033[m" "$3"
			;;
			yellow)
				printf "\033[33m%s\033[m" "$3"
			;;
			blue)
				printf "\033[34m%s\033[m" "$3"
			;;
			magenta)
				printf "\033[35m%s\033[m" "$3"
			;;
			cyan)
				printf "\033[36m%s\033[m" "$3"
			;;
			*)
				printf "Unknown color\n"
			;;
		esac
	;;
	-ncr | -crn) # RGB, no newline
		printf "\033[38;2;$2;$3;$4m%s\033[m" "$5"
	;;
	-nci | -cin) # Indexed color, no newline
		printf "\033[38;5;$2m%s\033[m" "$3"
	;;
	*) # echo with extra steps lmao
		printf "%s\n" "$1"
	;;
esac